name: Build release zip

on:
  push:
    branches:
    - production

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Generating zip
        uses: rudlinkon/action-wordpress-build-zip@1.3.0
        with:
          retention-days: 1 # Optional; defaults to 3
          install-composer: true # Optional; defaults to false
          npm-run-build: true # Optional; defaults to false
          node-version: 20 # Optional; defaults to 16

      - name: Zip Folder
        run: |
         cd dist-archive
         zip -r ../divi-barrierefrei.zip .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: latest
          tag_name: latest
          prerelease: true
          files: divi-barrierefrei.zip
          make_latest: true
